---
version: "3"
services:
 devopsdb:
   image: raghuram0024/mydbimage:dbimage
   ports:
     - "3306:3306"

 application:
   image: raghuram0024/myappimage:appimage
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
